service: app

provider:
	name: aws
	runtime: nodejs12.x
resources:
  Resources:
    QueueName:
      Type: "AWS::SQS::Queue"
functions:
	hello:
		 queueTestFunctionNt:
        handler: path/your/function/handler.handle
        events:
            - sqs:
                arn:
                    Fn::GetAtt:
                    - QueueName
                    - Arn